### ISSUE TITLE
ModelView => modelView

### ISSUE THREAD

**Issue by jamesplease** [jridgewell/minionette#13]
I understand the desire to capitalize this property, but it's inconsistent w. Backbone. The model class that you specify on Backbone collections goes under the `model` property, and not `Model`.

The same thing applies to `Region`, and any other of these props in Minionette.

**Comment by jridgewell** [comment]
This one I did make consciously. Constructors are always capitalized, and Backbone is silly for not following the convention. Re: https://github.com/jashkenas/backbone/issues/1765
