### ISSUE TITLE
Maybe refactor ModelView to not use `modelEvents`

### ISSUE THREAD

**Issue by jamesplease** [jridgewell/minionette#4]
It's cool that modelView comes with default events, but it's unfortunate that users need to re-write those events if they wish to extend the class. Maybe something like:

``` js
Minionette.ModelView = Minionette.View.extend({
    constructor: function(options) {
      this._listenToEvents(this.model, _.result(this, '_defaultModelEvents'));
      Minionette.View.apply(this, arguments)
    },

    // Listen to the default events
    _defaultModelEvents: {
        change: 'render',
        destroy: 'remove'
    },

    // The data that is sent into the template function.
    // Override this to provide custom data.
    serialize: function() {
        return this.model.attributes;
    }
});
```

this way, users can tack on their own `modelEvents` w.o. needing to repeat themselves. But maybe this was done intentionally.
# 

The same thing would apply [here](https://github.com/jridgewell/minionette/blob/master/src/collection_view.js#L18-L24), too.

**Comment by jridgewell** [comment]
A lot of Minionette is actually distilled from code I've written at work, and unfortunately, that's not available to reference.

Binding is done after [`#initialize` is called](https://github.com/jridgewell/minionette/blob/fe71c7d825d82692d9978b242074a293a2ce7ebb/src/view.js#L9-L18), so I've always solved it like so:

``` javascript
ModelView.extend({
    initialize: function(attrs, options) {
        this.modelEvents = _.extend({'event': 'method'}, this.modelEvents);
    }
});
```

**Comment by jamesplease** [comment]
Gotcha – makes sense. I could potentially see that pattern as something to mention in the docz.
