### ISSUE TITLE
Dangerous Underscore dep

### ISSUE THREAD

**Issue by jamesplease** [jridgewell/minionette#6]
I'm sure you keep up w. Underscore breaking changes, @jridgewell, but a `< 2.0` dep could cause issues for folks using Minionette who don't follow the changelog.

~~In fact, there's probably no reason to even include the dep, as this library doesn't use it at all.~~ :speak_no_evil: nvm, Github wasn't returning results for `_`.

**Comment by jridgewell** [comment]
I'm :-1: on this, as long as the library is using stable code. I don't want to limit the end dev to just what I've approved.

```
_.each
_.every
_.invoke
_.reduce

_.isFunction
_.isString

_.bindAll

_.initial
_.last
_.toArray

_.extend
_.omit
_.pick
_.result
```

I had thoughts about own-property shenanigans, but I think `_.extends` is going to stay the same now that `_.assign` has landed.
